#######################################################################################################
# Copyright (C) Compilation-Timer 2024                                                                #
# Module history:                                                                                     #
#   Date:       Author:                    Reason:                                                    #
#   18.01.2024  Gaina Stefan               Initial version.                                           #
# Description: This Makefile is used to give an example of how Compilation-Timer might get used.      #
#######################################################################################################

COMPILATION_TIMER = cd ../compilation-timer/bin && ./compilation-timer

### RULE AT THE BEGINNING OF THE COMPILATION ###
start:
	$(COMPILATION_TIMER) start

### RULE AT THE END OF THE COMPILATION ###
end:
	$(COMPILATION_TIMER) end
